### ISSUE TITLE
Fix scroll and add saving of conversations

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#135]
Problem 1
now: when I restart the app, all conversations are deleted. 
Should be: everything is saved, and once the app is restarted, the user is redirected to the list of conversations/summaries

Problem 2: 
Scroll is broken

See video for reference: https://drive.google.com/file/d/15rxa_ZyM89LamahmRwCKH47h4gxdc09F/view?usp=sharing

**Comment by josancamon19** [comment]
Should be solved with the latest internal testflight version
