### ISSUE TITLE
Are there videos or demos somewhere?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [BasedHardware/Friend#143]
Hi,

Very hyped by this project but I'm surprised to not find any pictures or videos online about it. Are there any?

Might be due to this: I'll be blunt but I do think it's better to hear this sooner than later: In my opinion the name "Friend", although very nice, seems terrible in SEO-wise. I really had trouble refinding this repo after having heard about it :/ I terribly want this kind of projects to thrive and find its community but this name really seems like trying in hardcore mode. I mean well :)

Thanks!

**Comment by after-ephemera** [comment]
@thiswillbeyourgithub thanks for the feedback! I don't think we have any videos online, but we have some great community-contributed docs [here](https://docs.basedhardware.com/). If you'd like to record some high-quality video I think that would be a great companion to the docs.

**Comment by thiswillbeyourgithub** [comment]
Hi, thanks for the answer, I somehow missed your message.

I'm fairly certain I stumbled upon a video of the project by the creator this morning on a crowdfunding website but I can't find it again! Is there a crowdfunding going on? If yes it's well hidden :o

**Comment by josancamon19** [comment]
@kodjima33
