### ISSUE TITLE
AppWithWearable: when using the app cannot find the device even the device is showing up

### ISSUE THREAD

**Issue by Rahul-1100** [BasedHardware/Friend#144]
when i run the app and am looking for the friend wearable device. The device is showing on Bluetooth search but app cannot detect any device
![image](https://github.com/BasedHardware/Friend/assets/152493001/be8e86e8-76d7-4911-85c4-36adea94e96f)
![Screenshot_20240511-204101](https://github.com/BasedHardware/Friend/assets/152493001/9efd587a-c30a-4584-bbb2-c38622933850)

**Comment by josancamon19** [comment]
Hey @Rahul-1100 can you try again with the latest version?

**Comment by Rahul-1100** [comment]
> Hey @Rahul-1100 can you try again with the latest version?

I am using the latest version of firmware as well as this repo.
I flashed the firmware both ways, first directly pasting the .uf2 file and building it according to the given method.

the firmware is recording as per the python script however it's still not being detected by the application.
![Screenshot_20240512-131815](https://github.com/BasedHardware/Friend/assets/152493001/e3cc6feb-d9da-4c49-8dbe-ade9b8af11f7)
![Screenshot_20240512-131758](https://github.com/BasedHardware/Friend/assets/152493001/6fe00547-40c9-4a8f-95bb-71a401c2994d)
![image](https://github.com/BasedHardware/Friend/assets/152493001/506ce4fb-0c80-44a9-bffd-f16d90f99833)

**Comment by Rahul-1100** [comment]
so basically I wasn't giving it location permission. After I gave it the permission. It detected the device. Thank you
