### ISSUE TITLE
Friend App UI not centered on fold interior display.

### ISSUE THREAD

**Issue by DJNighswander** [BasedHardware/Friend#147]
Found a minor UI bug where the Friend App UI doesn't seem to be centered on the interior screen of the Samsung Fold 5. I've attached screenshots to display the issue, which persists in all orientations.

![Screenshot_20240511_143941](https://github.com/BasedHardware/Friend/assets/12886912/f66bc663-94ed-4b14-b2be-27658f17c168)
![Screenshot_20240511_143932](https://github.com/BasedHardware/Friend/assets/12886912/82793053-187b-4c6d-a145-cc65a8d2559a)

**Comment by anmol-fzr** [comment]
Hi I would like to work on this issue, please assign me this one
