### ISSUE TITLE
Device disconnects when app is closed

### ISSUE THREAD

**Issue by wdcampbell3** [BasedHardware/Friend#189]
So I got the latest APK installed, added my deepgram and openai apis. It connected, the red light turned blue, started working correctly and I saw the text being generated. However, about a minute after leaving the app, the blue light turns red. When I open up the app again, there's no memory of any of the previously recorded text, but a device does reconnect and then starts working again. Is there some sort of permission on my pixel 8 that I haven't enabled? (Allow background usage is already enabled)

**Comment by ragincajunbanjo** [comment]
Have you tried "pause app activity if unused"?

**Comment by wdcampbell3** [comment]
That setting was turned on so I turned it off. I just installed the latest 1.0.6 and the device still connects successfully and see the transcription start. However the blue light still turns red after about 30 seconds when I leave the app. When I Open the app again It reconnects without an issue. I have a pixel 8 with the latest firmware...
