### ISSUE TITLE
Android App Permissions 

### ISSUE THREAD

**Issue by ragincajunbanjo** [BasedHardware/Friend#200]
Hello.

When opening the app, I get a window that asks for location and Bluetooth permissions. However, it takes me to the settings page and those aren't options. The app never requests those permissions, which is required in Android 14.

Phone: Google Pixel 8 Pro
OS: Android 14
Android Build: AP1A.240505.004
App Version: 1.0.1

**Comment by josancamon19** [comment]
Hey @ragincajunbanjo pls try this release https://github.com/BasedHardware/Friend/releases/tag/v1.0.6-android
