### ISSUE TITLE
Only records/transcribes when actively paired to device?

### ISSUE THREAD

**Issue by RwnQ8** [BasedHardware/Friend#208]
Hopefully I'm missing something here because otherwise this is a major bummer… It seems that after using the device for a day that only conversations while the device is within range and actively paired to my mobile device are recorded and transcribed in the app?

**Comment by rwnq8** [comment]
Wow, the silence is deafening. Good thing I spent under $100 on this thing. I freely admit that I am a reluctant hack for AI's infinite opportunity if only the dev teams making this stuff could get their heads out of code and see the big picture.

**Comment by akshaynarisetti** [comment]
Hi, we have plans to add this in the upcoming version of the Device we have in the works.
