### ISSUE TITLE
Build failed: Missing required property 'storeFile' in SigningConfig 'release'

### ISSUE THREAD

**Issue by PriyanshuMallick** [BasedHardware/Friend#215]
I am experiencing a build failure when trying to create a release APK for your Flutter application "AppWithWearable". The error message indicates that the SigningConfig "release" is missing a required property storeFile. Below are the details of the error.

Error Message:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > SigningConfig "release" is missing required property "storeFile".
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 1m 26s
Running Gradle task 'assembleRelease'...                           87.6s
Gradle task assembleRelease failed with exit code 1
```

Request:
I would appreciate any assistance or guidance on resolving this issue. If there are any additional configurations or steps I need to follow, please let me know.
Thank you for your support.

**Comment by francip** [comment]
Follow https://github.com/BasedHardware/Friend/blob/main/apps/AppWithWearable/README.md. (If you don't have any key, you can skip step 5)

Specifically, make sure your **.env** has all the entries from **.env.template** and run `dart run build_runner build` once to autogenerate the correct **env.g.dart** file.

**Comment by PriyanshuMallick** [comment]
We did all the things mentioned in the doc/readme and the app works fine when we try to run it in debug mode

But its just that we are not able build the apk for the app

**Comment by francip** [comment]
Oh! I misunderstood the failure.


Have you made the code signing? You need to have your own certificate and provisioning profile, so Xcode can sign the .apk.
Here's my local changes, so I can sign with my certificate/provisioning profile - https://github.com/BasedHardware/Friend/commit/8eb39b059b284be8de8ed15b09acdccb3bc0ee66

Other than that, I am not sure what the failure might be. :-/
