### ISSUE TITLE
if wearable is disconnected, or if app is crashed, or if app is closed, we should still save the memory ($300)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#220]
if wearable is disconnected, or if app is crashed, or if app is closed, we should still save the memory

Right now if you disconnect the wearable, nothing is saved 

Reference: 
https://discord.com/channels/1192313062041067520/1193276519867482242/1247787503860318248

**Comment by josancamon19** [comment]
This one is actually easy, whoever wants to take it: store the bytes processed wav_bytes.dart in shared preferences, clean them when they get cleaned, and then when the app connects or opens again or this function is called again `initiateBytesProcessing`, simply check if there are bytes on preferences, and try creating a memory with those

**Comment by priyanshukumar397** [comment]
**Solution:**

**We can add a function where when the app crashes for whatsoever reason - the function will save the user changes/data before closing without user explicit permission (only in case of crashing due to unknown issues). This way the user changes/data will be saved even if the app crashes due to certain circumstances.** @kodjima33

**Comment by josancamon19** [comment]
Just added this on `transcript.dart`.

```dart
  _processCachedTranscript() async {
    debugPrint('_processCachedTranscript');
    var segments = SharedPreferencesUtil().transcriptSegments;
    if (segments.isEmpty) return;
    String transcript = _buildDiarizedTranscriptMessage(SharedPreferencesUtil().transcriptSegments);
    File file = await WavBytesUtil.createWavFile(SharedPreferencesUtil().temporalAudioBytes);
    String? fileName = await uploadFile(file);
    processTranscriptContent(context, transcript, fileName, file.path, retrievedFromCache: true);
    SharedPreferencesUtil().transcriptSegments = [];
  }
```

The only missing portion it's in case the user had many audio bytes streamed to the app, but was offline, we could check if .temporalAudioBytes is not empty, call the transcribe endpoint, and then create the memory.
