### ISSUE TITLE
Simulation envorinment for people to record audio without the device ($1000)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#221]
Many people don't have wearables. We need to let people to be able to contribute in 2 minutes without the werarable. 

NEed to create a simulation environment to "simulate" the wearable with a computer

This is a paid task. Reward is $1000 in cash. Simply link your PR with this task and we will check it asap

**Comment by ebariaux** [comment]
First go at this in https://github.com/BasedHardware/Friend/pull/225

**Comment by kodjima33** [comment]
Added +$500 for this task. Now $1k total

**Comment by ebariaux** [comment]
Took a quick look at Web Bluetooth specs, it only supports Central role, not Peripheral (see https://webbluetoothcg.github.io/web-bluetooth/#introduction).
i.e. you can connect to a device but not act as one.

If somebody wants to have a go at this, I suppose it'll need to be "native" on WIndows/Linux, as I did for macOS.
