### ISSUE TITLE
Allow plugins to integrate with chat ($500)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#223]
Plugins prompts should have access to affect chat's conversations 

As a user, if I enable a "strict mentor" plugin, I  want the conversational style of chat to be more strict 

This is a paid task. Reward is $500 in cash. Simply link your PR with this task and we will check it asap

**Comment by kodjima33** [comment]
Removed notifications - now this task is only about the chat

**Comment by diegoasua** [comment]
some steps toward this https://github.com/BasedHardware/Friend/pull/276
