### ISSUE TITLE
Reminders integration

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#224]
A previous PR (discontinued): https://github.com/BasedHardware/Friend/pull/230

Correct, not every single action item is worth a calendar or something.

**Part 1**

Prepare a few keyword phrases

"Hey Friend" Remind me to do X at y time.

During the transcript processing every 30 seconds, it should find if there's this keyword phrase

And, ask GPT to analyze the transcript, and structure the key points, "time" "date" "title", "description" optional.

With that, check which reminders platform the user has configured.

**Part 2**

During memory creation, it should extract a list of events to be scheduled `generateTitleAndSummaryForMemory` and those should be created

**Part 3**

Testability of feature.
We create them automatically, or we create drafts of them, so the user includes those events manually to avoid clutter.

It should be easy from the code to change between these 2 options.

**Platforms to be configured.**

- Google Calendar (main)
- Apple Reminders

-------

**Screens:**

So settings should have 2 things, an authorize "Friend" to use calendar and reminders, and one to select which of those to use.

Additionally on onboarding, it should have the option to authorize each of the platforms, or simply skip.

Finally, the memory object should have a events created list, which contain all that data above + platform used, and that should be displayed in the memory_detail page.

NOTE: ideally no backend need, but if so, happy to help.

----

**Comment by diegoasua** [comment]
I am looking into this. Which platforms do we want to support? Some that come to mind

- Apple Reminders
- Google Calendar
- Notion
- Obsidian

The assistant is incentivized to create action points from the conversation. I don't think every single action point should be a reminder it would get too cluttered and no one would use the feature. So what constitutes a reminder and what doesn't? The other approach is that the assistant identifies reminders, which is potentially a subset of action points, and asks the user for confirmation to write to whichever reminders app has been selected as default.

**Comment by josancamon19** [comment]
A previous PR (discontinued): https://github.com/BasedHardware/Friend/pull/230

Correct, not every single action item is worth a calendar or something.

Let's do the following:

Prepare a few keyword phrases

"Hey Friend" Remind me to do X at y time.

During the transcript processing every 30 seconds, it should find if there's this keyword phrase

And, ask GPT to analyze the transcript, and structure the key points, "time" "date" "title", "description" optional.

With that, check which reminders platform the user has configured.

Platforms to be configured.
1. Google Calendar (main)
2. Apple Reminders

-----

**Screens:**

1. So settings should have 2 things, an authorize "Friend" to use calendar and reminders, and one to select which of those to use.

2. Additionally on onboarding, it should have the option to authorize each of the platforms, or simply skip.

3. Finally, the memory object should have a events created list, which contain all that data above + platform used, and that should be displayed in the memory_detail page.

NOTE: ideally no backend need, but if so, happy to help.

**Comment by taaha161** [comment]
Hi, I would like to work on this. Can you please assign this to me?

**Comment by josancamon19** [comment]
Assigning to @diegoasua for the next 2 days

**Comment by diegoasua** [comment]
#307 WIP

**Comment by mdmohsin7** [comment]
@josancamon19, I would like to take on this task and give it a try if it's still available.

**Comment by antonio-pedro99** [comment]
Hi @josancamon19, have worked on a similar task before. Can I take this?

**Comment by josancamon19** [comment]
Assigning to @antonio-pedro99 please create a Draft PR when you get started.
Join discord and say Hi :)

**Comment by antonio-pedro99** [comment]
> Assigning to @antonio-pedro99 please create a Draft PR when you get started. Join discord and say Hi :)

I will be there

**Comment by josancamon19** [comment]
Hi @antonio-pedro99 if you could create a Draft PR it'll be great so we can see progress, otherwise I will have to unassign the task, as I don't see progress, thanks!

**Comment by antonio-pedro99** [comment]
> Hi @antonio-pedro99 if you could create a Draft PR it'll be great so we can see progress, otherwise I will have to unassign the task, as I don't see progress, thanks!

I will send a draft PR by tonight

**Comment by josancamon19** [comment]
No relevant progress made. Unassigning.

**Comment by antonio-pedro99** [comment]
@josancamon19 
> No relevant progress made. Unassigning.

Did you know that we have jobs? 😁 and we work on open source on our free time?

Maybe next, you should include estimated time to finish the issue. This will help us pick issues we will have enough time to work on :).

**Comment by josancamon19** [comment]
Yes, I understand, but the 2 commits you made, were only after I asked for an update, and you had like 4 days before that.

You should've shared some progress within the first 2 days of the task.

**Comment by josancamon19** [comment]
Part 2 and 3 ready in development, comments on part 1 as not sure if that's the right use case.

**Comment by josancamon19** [comment]
Next part of this should be integrate directly with Google calendar.
