### ISSUE TITLE
delete this stupid fucking shit ($0)

### ISSUE THREAD

**Issue by authenyoo** [BasedHardware/Friend#238]
Fuck this  shti

**Comment by MikeKMiller** [comment]
???

**Comment by polymorphicshade** [comment]
I agree with OP.

What is the point of this if we can't self-host everything? (unless I'm misunderstanding the readme)

**Comment by MikeKMiller** [comment]
There is nothing to host. It is self contained in the app, and wearable.

**Comment by authenyoo** [comment]
Lil B would not approve of this.

**Comment by MikeKMiller** [comment]
Who is 'Lil B'?

**Comment by polymorphicshade** [comment]
> There is nothing to host. It is self contained in the app, and wearable.

...but everything goes through Deepgram first right? Why bother open-sourcing a front-end app like this when the actual important part is being sent to another company's servers?

I hope I'm drastically misunderstanding this...

**Comment by MikeKMiller** [comment]
There is work being done to do the transcription with Whisper. The initial release is using Deepgram.
