### ISSUE TITLE
In Connected Device View of App, the Sound Animation Seems to be Arbituary

### ISSUE THREAD

**Issue by garyyjn** [BasedHardware/Friend#241]
Can be misleading and confusing for figuring out where is a issue is, whether the issue is with OpenAI API or device microphone or wireless connection.

**Comment by bbookman** [comment]
Would be great to give user some feedback if the app "is listening" and how much it "hears".  I highly recommend this icon or animation live in the outside bar of the app UI near the battery indicator or somewhere there.

IMO this is cosmetic, but user friendly P2

**Comment by bbookman** [comment]
IMO P2.  good quality of life issue for users, however not core MVP IMO

**Comment by josancamon19** [comment]
Dont thin kstill applies
