### ISSUE TITLE
Formatting error in "Install firmware" page in docs

### ISSUE THREAD

**Issue by JaryJay** [BasedHardware/Friend#242]
In https://docs.basedhardware.com/assembly/Install_firmware/, the step numbers are formatted incorrectly. It should be 1,2,3,4,5,6, but due to the image about "Open an existing application", the order is 1,2,1,2,3,4 instead.

First two steps
![image](https://github.com/BasedHardware/Friend/assets/47123100/fb706c94-ea49-47de-a4c5-c0bdc4bf3f43)
Next few steps (note that it should start at 3, not 1 again)
![image](https://github.com/BasedHardware/Friend/assets/47123100/7c984378-84d8-4e33-8a7f-1ec89ebc9fc3)

**Comment by acratophorux** [comment]
This is resolved. You may close it now.
