### ISSUE TITLE
error when compiling for iOS

### ISSUE THREAD

**Issue by diegoasua** [BasedHardware/Friend#249]
I followed the [steps](https://docs.basedhardware.com/get_started/Setup/) to install `AppWithWearable` and compile for mac M-series

`flutter run` fails with:

```
Launching lib/main.dart on Diego’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 
Running pod install...                                           1,108ms
Running Xcode build...                                                  
Xcode build done.                                           19.3s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): lib/env/env.dart:3:6: Error: Error when reading 'lib/env/env.g.dart': No such file or directory
```

**Comment by diegoasua** [comment]
I see this was a problem in the app without wearable addressed [here](https://github.com/BasedHardware/Friend/blob/main/apps/AppStandalone/README.md)

However that one is for the standalone app. What it suggests wouldn't work for the app with wearable since API secrets come from the app itself according to the [guide](https://docs.basedhardware.com/get_started/Setup/)

**Comment by diegoasua** [comment]
Alright some progress. Guide needs to be updated, missing one step:

```bash
dart run build_runner build
```

that generates `lib/env/env.g.dart`. However the Pinecone key is giving issues.

```
[INFO] Generating build script completed, took 159ms
[INFO] Reading cached asset graph completed, took 65ms
[INFO] Checking for updates since last build completed, took 773ms
[SEVERE] envied_generator:envied on lib/env/env.dart:

Environment variable not found for field `pineconeApiKey`.
package:friend_private/env/env.dart:21:17
   ╷
21 │   static String pineconeApiKey = _Env.pineconeApiKey;
   │                 ^^^^^^^^^^^^^^
   ╵
[INFO] Running build completed, took 343ms
[INFO] Caching finalized dependency graph completed, took 53ms
```

Same for the Pinecone index URL and the index namespace. I can comment all three out in `lib/env/env.dart` and then `env.g.dart` generates successfully. But App compilation would fail with 

```bash
Running Xcode build...                                                  
Xcode build done.                                           10.4s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): lib/backend/api_requests/api_calls.dart:264:20: Error: Member not found: 'pineconeIndexUrl'.
```

**Comment by francip** [comment]
The app read me has been updated and should be correct now.

**Comment by francip** [comment]
You need to update your .env file to contain all the keys in .env.template

**Comment by diegoasua** [comment]
I think we should also either update the installation guide in the website or somehow point to the Readme being the source of truth
