### ISSUE TITLE
Reprocess memories with community plugins 

### ISSUE THREAD

**Issue by RwnQ8** [BasedHardware/Friend#258]
As a user I want to be able to retrospectively update memories with community plug-ins that may not have been available or selected when the memory was created.
![singularity - 1](https://github.com/BasedHardware/Friend/assets/167072747/7eae8a04-68ea-4e7f-a661-64ccdd090a08)

**Comment by diegoasua** [comment]
This could be an option when sliding the memory right and left. Something like this:

![image](https://github.com/BasedHardware/Friend/assets/36935934/5f73a45c-d0b8-41f2-99ee-d18d5c156339)

**Comment by bbookman** [comment]
IMO P2 as not core MVP

**Comment by josancamon19** [comment]
Done, kinda.

You'd have to have that plugin enabled when reprocessing the memories.

Let me know if this works, we will be releasing better plugins functionality in the following days.
