### ISSUE TITLE
Batch Export Memories/Save to Cloud

### ISSUE THREAD

**Issue by RwnQ8** [BasedHardware/Friend#259]
As a user fine-tuning LLM interactions I'd like to be able to have memories and ideally chats as well auto-save off device somewhere in iCloud or WebDAV; or at least manually batch export everything somewhere other than to Google.

**Comment by bbookman** [comment]
is your request something different than what is currently implemented as a Developer Mode storage feature with GCP?  If so, I agree.  Need additional options such as DropBox or Google Drive.

**Comment by rwnq8** [comment]
Yes, thinking send to WebDAV/S3 compatible endpoint (using Cloudflare R2 bucket atm)

**Comment by josancamon19** [comment]
Duplicate of #281
