### ISSUE TITLE
End Conversation Button or iOS shortcut

### ISSUE THREAD

**Issue by TPGLLC-US** [BasedHardware/Friend#278]
**Is your feature request related to a problem? Please describe.**

I have an issue with my conversations blending together because I go from one conversation to another quickly. It becomes difficult to distinguish where one conversation ends and the next begins and then the plugins are applied to a blended conversation. 

**Describe the solution you'd like**

I would like to request an "End Conversation" button or iOS shortcut integration. This feature would allow me to clearly mark the end of one conversation and the beginning of another, ensuring that my conversations are accurate and separated properly.

**Describe alternatives you've considered**

An alternative solution could be implementing a voice command that triggers the end of a conversation, but an "End Conversation" button or iOS shortcut would be more practical and efficient for my use case.

**Additional context**

This feature would greatly improve the usability of the transcriber pendant for users who have frequent and quick conversations. It would also enhance the overall accuracy of the transcriptions by preventing conversations from blending together.

**Comment by bbookman** [comment]
IMO P2.  would make a quality of life difference to users, but not MVP IMO
