### ISSUE TITLE
Remove a discarded memory flag to process it as a memory or add a memory to the discarded

### ISSUE THREAD

**Issue by darklite80** [BasedHardware/Friend#279]
Can we add the ability to inside the discarded memory 3dot menus to move  the discarded memory to just a memory and initiate the processing of it. 

Also to be able to flag a memory to move it to discarded memory.

**Comment by josancamon19** [comment]
Makes a lot of sense

**Comment by josancamon19** [comment]
https://github.com/BasedHardware/Friend/assets/18078879/34af6af9-c8c4-4e40-8f79-dddcca502fb4

Releasing in next version 1.0.9
