### ISSUE TITLE
App stops running when it’s in background or locked

### ISSUE THREAD

**Issue by akshaynarisetti** [BasedHardware/Friend#28]
Currently the App isn’t Actively running when it’s minimized or the if the user locks the device in itself.

**Comment by TPGLLC-US** [comment]
I am having the same issue now 
iPhone 14 Pro Max
iOS 17.5.1
When app is running in background friend disconnects without notification
Friend status led remains blue

**Comment by akshaynarisetti** [comment]
If the LED is blue it’s probably connected, does it show disconnected in the App?
