### ISSUE TITLE
On iOS Friend App. Speech profile setup will reset itself after some time and will not process or capture.

### ISSUE THREAD

**Issue by darklite80** [BasedHardware/Friend#280]
Randomly the speech profile will show it needs setting up again and the friend stops sending speech to capture when this happens. 

This problem is random and seems to happen after the app has been running for a few hours. 

Lost half a day's worth of interactions.

**Comment by josancamon19** [comment]
Speech profile is in MVP terms, as rn we use deepgram again, it's not working at all, we are working on a production whisper-x version, which will be able this week, and the work on this will be continued then.

**Comment by bbookman** [comment]
IMO P2 as not core MVP
