### ISSUE TITLE
iOS notes, iCloud files, onenote, OneDrive integration.

### ISSUE THREAD

**Issue by darklite80** [BasedHardware/Friend#281]
In app can you also have the option to save recordingsto OneDrive/iCloud files and also auto export a daily summary to a onenote, iOS note, google doc etc

**Comment by bbookman** [comment]
upvote

**Comment by nathansudo** [comment]
I'd love to see Google Drive added to this mix but if it can be stored to the phone and I could choose the location, I could also back it up automatically on my end using Pcloud or whatever storage we want individually too.

**Comment by bbookman** [comment]
another vote to start with Google Drive

**Comment by bbookman** [comment]
btw this is really at least 2 feature requests.  

- In app can you also have the option to save recordings to external source other than google bucket
- auto export a daily summary to a onenote, iOS note, google doc etc

taking it upon myself to split this into 2

**Comment by bbookman** [comment]
See #283 , #284 , #285 , #286

**Comment by diegoasua** [comment]
Can we also have Notion & Obsidian as export options? They both take markdown

**Comment by nathansudo** [comment]
@diegoasua Adding another vote for Notion, I was just thinking of storage but memories being sent to Notion would be amazing, we can probably do that now with the share feature and select Notion but how much better having a direct integration!

**Comment by josancamon19** [comment]
What do you plan to use this for, guys? @bbookman @darklite80 @nathansudo 

Just wondering, you get them on each of those platforms, then what happens? Thanks

**Comment by darklite80** [comment]
Currently I have a onenote set up as a daily journal. The structure for my onenote for sorting purposes is

NOTEBOOK 
-FRIEND JOURNAL

SECTION
-MONTH & YEAR (06-2024)

PAGES
-DATE(JUNE 15-1530hrs)

This set up is how daily I go through and share my memories to onenote for that day to a new page with the date group it's tedious to do every day but it it could sync it would be much better. So monthly all I would have to do is make a new month section and point the pages to create pages on that new section.

**Comment by bbookman** [comment]
> What do you plan to use this for, guys? @bbookman @darklite80 @nathansudo
> 
> Just wondering, you get them on each of those platforms, then what happens? Thanks

A number of users have been asking this.

1. To use audio tools outside or the Friend app 
2. To use as a backup
3. Because there are folks who are concerned about security/privacy
4. To set up integrations outside of the app

**Comment by darklite80** [comment]
I'd like to be able to back up the memories that are important in my OneNote journal. No privacy concerns just if I want to add my own notes about the memory it's easier if it is exported to my OneNote journal. I can make notes add to where appropriate or easily export like say a meeting to word if I need to note the minutes better

**Comment by josancamon19** [comment]
@darklite80 I'm creating a backup feature rn, non-dev focused.

This issue will have low priority as it is a dev feature, but if anyone is happy to implement it, I'm happy to receive and review PR's

**Comment by andresgomezsar** [comment]
We could maybe start with having an import in JSON. As far as I know we currently have a way of exporting memories in JSON but there is no way to import a JSON file. Would be nice to have a reliable file-based backup system that can work with any storage service, not just the few that are integrated.

**Comment by diegoasua** [comment]
I think the new version has a backup export under dev settings

**Comment by bbookman** [comment]
> @darklite80 I'm creating a backup feature rn, non-dev focused.
> 
> 
> 
> This issue will have low priority as it is a dev feature, but if anyone is happy to implement it, I'm happy to receive and review PR's

So just to be clear, you were working on a feature for a non-Dev. I'm assuming something like what was originally proposed here and this ticket.

And more of the discussion here is focused on something like JSON?

**Comment by bbookman** [comment]
> I think the new version has a backup export under dev settings

Setting at the bottom of Dev Mode UI. 

I'm assuming the way it's implemented you get every transcription ever time you export @josancamon19 

I haven't had a chance to try it yet

**Comment by bbookman** [comment]
I think the core of this request is to allow export of all user generated assets such as audio, raw text, entire memory including plug-in results.  And export in a consumer facing manner

Each of the above could be split out in terms of tasks.  however the filing OP here is requesting at least one

**Comment by bbookman** [comment]
IMO P1 as long as bugs exist preventing memory creation.  Could revisit when those are handled.  Also this feature is not MVP IMO

**Comment by ccjeff** [comment]
Wondering if this is implemented. Would love to have alternative storage options like s3
