### ISSUE TITLE
Give part numbers for Amazon in buying Guide

### ISSUE THREAD

**Issue by mattgreeley** [BasedHardware/Friend#282]
I bought the switch off amazon but the default option was SS12F44.

But that did not fit nicely in the hole in the case.

Going to try SS12D00 now as it appears to match the picture better.

But gap in case still seems really small relative to switch.

Would be great to have a specific part number.

![image](https://github.com/BasedHardware/Friend/assets/62221195/77c4726c-985d-4bfc-866d-c6116df99248)
![image](https://github.com/BasedHardware/Friend/assets/62221195/716bef41-31f8-4ae6-9d57-89554bd0d473)

**Comment by francip** [comment]
kodjima33 what's the exact switch model to use?

**Comment by mattgreeley** [comment]
SS12D00 fits.  I'll PR the docs when I have a moment.

**Comment by kodjima33** [comment]
SS12D00
