### ISSUE TITLE
App can be used without device

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#289]
To better onboard users, and allow everyone to use the app.

We need to enable people to use their phone microphone as audio source.

- The onboarding find_devices page should have a skip button, to start the app without device.
- At capture there should be a start and stop recording buttons, when there's no device.
- Device related tabs should consider this and display accordingly
- When app on the background the recording should continue.
- When the app is being used just with phone microphone, the device should be "advertised" some places on the app so people buy it.

**Comment by georonathan47** [comment]
I'm working on this

**Comment by georonathan47** [comment]
@josancamon19 please assign me to this issue

**Comment by josancamon19** [comment]
Assigned to @georonathan47 for the next 2 days

**Comment by josancamon19** [comment]
@georonathan47 this has a bit of a high priority right now, do you have any blockers?

**Comment by georonathan47** [comment]
> @georonathan47 this has a bit of a high priority right now, do you have any blockers?

Sort of... Even though i've been able to add the skip button that sends the user to the homepage, I still don't seem to find my way around the app (in terms of navigation)

**Comment by georonathan47** [comment]
hello @josancamon19 
I tried to create a branch and push my changes there but this is what i got in my terminal:
`remote: Permission to BasedHardware/Friend.git denied to georonathan47.
fatal: unable to access 'https://github.com/BasedHardware/Friend.git/': The requested URL returned error: 403`

**Comment by josancamon19** [comment]
Plese do a fork, send your changes to your branch @georonathan47 and then create a PR

**Comment by georonathan47** [comment]
@josancamon19 any progress on this?

> hello @josancamon19 I tried to create a branch and push my changes there but this is what i got in my terminal: `remote: Permission to BasedHardware/Friend.git denied to georonathan47. fatal: unable to access 'https://github.com/BasedHardware/Friend.git/': The requested URL returned error: 403`

**Comment by josancamon19** [comment]
You should do a fork of the repo, then you create a PR from there to this repo

**Comment by georonathan47** [comment]
oh ok. thanks

**Comment by josancamon19** [comment]
Please lmk when you create this PR @georonathan47

**Comment by josancamon19** [comment]
I'll wait for the next 4 hours for this, otherwise will close it this. @georonathan47

**Comment by mdmohsin7** [comment]
@josancamon19 I would like to take up this task if it's still available.

**Comment by josancamon19** [comment]
Removed bounty for this task, taking it myself as @georonathan47 was non responsive and didn't see any updates at all.

**Comment by bbookman** [comment]
IMO P3, not part of MVP and not critical path

**Comment by josancamon19** [comment]
This is mostly done, moving to #348 to finish it and will be released
