### ISSUE TITLE
[P1] Community communication: known issues and work arounds

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#290]
At some reasonable cadence (daily?) send discord message highlighting key know issues and potential work arounds.

**Comment by bbookman** [comment]
Perhaps this could be satisfied with release notes. Release notes should include what was fixed a link to that fix from GitHub as well as known issues with a link to the issue in GitHub.

**Comment by bbookman** [comment]
P1 as it is not MVP, however I feel critical to community health

**Comment by josancamon19** [comment]
Closing it for now, friend changelog seems to be working
