### ISSUE TITLE
[P1] Community Communication: milestones and targets

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#292]
First I just noticed GitHub issues have this thing called milestone not sure how that works. 

I believe the project needs steaks in the ground with the understanding that like every project they're going to be hurdles where you won't meet targets. 

However, it would be great to see a three month six month plan for development.

**Comment by josancamon19** [comment]
Setup a single source of truth were people and pin it on discord were everyone has an idea of what are we working on

**Comment by bbookman** [comment]
I would be happy to help make this effort succeed. Let me know if there's anything I can do.

**Comment by bbookman** [comment]
This is a P1 as it is not part of product MVP, however I think it is critical for success of the project to manage the project via plans.  Happy to help if I can.
