### ISSUE TITLE
Queue UI for pending memories

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#293]
A visual queue showing memories waiting to be generated. Indicate status like "Pending" "generating". Also include initial time stamp and estimate completion time. 

Remove item from Queue when memory completes

**Comment by josancamon19** [comment]
It takes time more or less because of the google cloud bucket upload (developer mode), LLM inference takes 1-2 seconds, so for most people is kinda instant, we'll probably make a beautiful animation for it later, but rn it is not a big deal for most people.

**Comment by bbookman** [comment]
Why decide a feature request as not planned without consulting the community?  If what is intended is a "beautiful animation" I'd recommend creating a new issue to track that.  who decides that something is not scheduled and not worthy of planning?
