### ISSUE TITLE
User defined STT bias

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#294]
Allow user to define X number of words and perhaps phrases. And use provide negative or positive bias values. Typical bias values in code tend to be not user-friendly. Create a more user-friendly scheme for positive and negative biasing for the user.

Also biasing 10 to be odd for user  bc typically it isn't clear to user what happens when one biases a word "7" bc it's possible to over-bias. Figure out a scheme so user does not over bias. 

Maybe start with "high/ medium/ low" as user choices and in background those resolve to sensible on code bias.

**Comment by josancamon19** [comment]
This will be possible in a couple of months with more robust plugins, closing for now.

**Comment by bbookman** [comment]
Software teams do not close issues when they are scheduled for a later time.  What the do is schedule them for a later time and leave them open
