### ISSUE TITLE
STT processing queue

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#295]
User would like to know that some audio was Captured and not yet transcribed. That transcription from a date time is processing

**Comment by josancamon19** [comment]
I don't understand, can you add more detail

**Comment by bbookman** [comment]
Right now audio is captured, but it takes time for that audio to process.  From the UI, I have no idea that any processing of audio captured at a specific date time really is happening.  As a specific example:  I attend a meeting at 1pm.  At 1:30pm I still see no memory.  I'd like to know that the audio is still processing.

It's a queue.  But the UI has no visibility into the queue

I'm happy to mock up something if this is still not clear as to what it might look like.  It should look like a queue ;)

**Comment by josancamon19** [comment]
Huh there shouldn't be 30 min of audio in a queue. You see the transcript?

1. Well it takes 2 minutes of silence for a memory to be processed, maybe it's that.
2. Audio is processed every 30 seconds so you should see it in capture.

if there's an issue with audio not appearing in capture, please re open, or in case even with 2 minutes of silence memory is created.
