### ISSUE TITLE
Stamp discard with Discard reason

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#296]
I assume the speech to text services return some sort of reason that they can't transcribe the audio. Really I assume the only couple reasons are it's unintelligible or it's too short. Regardless, it would be great to add information to the discarded transcripts as to why it was discarded.

**Comment by josancamon19** [comment]
Hey, @bbookman why you'd like to know this?

**Comment by bbookman** [comment]
> Hey, @bbookman why you'd like to know this?

As a user I'm at a loss as to why my memory is discarded.  Did that happen because there was too little audio to process?  Did it happen because of a connectivity issue?  Beyond the user wanting to understand what the app is doing, this has a benefit of giving the user more tools to report problems.  A tool for devs to debug

**Comment by josancamon19** [comment]
You can look at the prompt in the code :) 

```
Based on the following recording transcript of a conversation, provide structure and clarity to the memory in JSON according rules stated below.
The conversation language is $languageCode. Make sure to use English for your response.

It is possible that the conversation is not worth storing, there are no interesting topics, facts, or information, in that case, output an empty title, overview, and action items.  
     
    For the title, use the main topic of the conversation.
    For the overview, use a brief overview of the conversation.
    For the action items, include a list of commitments, scheduled events, specific tasks or actionable steps.
    For the category, classify the conversation into one of the available categories.
```
    
``It is possible that the conversation is not worth storing, there are no interesting topics, facts, or information, in that case, output an empty title, overview, and action items. `` ~ This determines if discarded or not.

I modified the prompt yesterday because it was discarding memories too much, this should be fixed on next release.
Closing this issue, there's no priority on determining why it was discarded.

**Comment by bbookman** [comment]
What i wrote reads "As a user".  Users can't read code.  Users do not wish to be blind as to why the most central feature of the product is not executing.  "Read the code" is not a solution to this real user need

**Comment by bbookman** [comment]
I'm lobbying for a P1 here.  User's want to know
