### ISSUE TITLE
Create a multi-environment app (development/production) [$300]

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#297]
**Is your feature request related to a problem? Please describe.**
Been able to test changes easily, and bring more stability to releases.

**Describe the solution you'd like**
The app should have development and production environments, which allow to have appId for development finished a `.dev`, and also allow to use different `.env` file for each version.

This should work for android and ios.

**Describe alternatives you've considered**
We've seen at flutter flavorizr, and other flutter docs `https://docs.flutter.dev/deployment/flavors` 

**Additional context**

THIS IS A PAID TASK ($300). TO COMPLETE IT AND RECEIVE A BOUNTY, CREATE PULL REQUEST

**Comment by TekExplorer** [comment]
What do you need that isn't supplied by simply checking `kDebugMode`?
You need to keep environment variables separated regardless right?

**Comment by georonathan47** [comment]
> **Describe the solution you'd like** The app should have development and production environments, which allow to have appId for development finished a `.dev`, and also allow to use different `.env` file for each version.

I don't understand the `.dev` file... What's its purpose? Is it really needed?

**Comment by ologunB** [comment]
I am already on this.

**Comment by georonathan47** [comment]
> I am already on this.

I've also started🤣

**Comment by georonathan47** [comment]
> I am already on this.

I'll leave it for you, then

**Comment by ologunB** [comment]
Haha. Alright, thanks.  @georonathan47

**Comment by TekExplorer** [comment]
I dont see the point of being "on this" if it's not clear what is desired here. I don't know of anything this is asking for that even needs flavors in the first place.

**Comment by ologunB** [comment]
It is clear enough though.

1. Add flavour to the app so the app ids are different and dev can be run independent of the prod
2. Use a .env variant so that the parameters of dev and prod are different. @TekExplorer

**Comment by josancamon19** [comment]
Please keep posting updates, will keep it to you for the next 2 days

**Comment by josancamon19** [comment]
Reviewing @costa96 PR

**Comment by ologunB** [comment]
#306 should fix the above issue

**Comment by josancamon19** [comment]
lgtm, please dm on discord your transfer details to @kodjima33

**Comment by josancamon19** [comment]
@ologunB please remove the app identifier from your apple account 
![CleanShot 2024-06-22 at 12 14 28@2x](https://github.com/BasedHardware/Friend/assets/18078879/4e682d3c-3a34-46cb-8fb7-613bfe3e2963)

**Comment by ologunB** [comment]
Okay. Will try to remove it today.

**Comment by josancamon19** [comment]
let me know @ologunB

**Comment by ologunB** [comment]
Its being removed

**Comment by ologunB** [comment]
Its being removed @josancamon19

**Comment by josancamon19** [comment]
Thanks @ologunB 

Still cant :( let me know if I can help

https://github.com/BasedHardware/Friend/assets/18078879/4f2da739-385c-4094-b866-1171b0142a96

**Comment by ologunB** [comment]
I have actually deleted it unless someone else also used it. I'm suggesting
of changing the .dev suffix to .develop. Are you open to that? I can easily
do that today in just a commit.

**Comment by josancamon19** [comment]
Yes please, that works, thanks.

**Comment by josancamon19** [comment]
Hey, amazing work @ologunB thank you so much for the help!

Don't forget to share your transfer details to joan.santiago.cabezas@gmail.com

**Comment by ologunB** [comment]
@josancamon19 i have sent a mail to the email above and message to @kodjima33 on discord server but I'm yet to get a response.
