### ISSUE TITLE
We're notifications should be permanently visible someplace

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#299]
I just got an error notification in the app. But accidentally dismissed it. It's now gone. 

Please add a spot somewhere on the app that allows users to view errors with date/time stamp. Helps report bugs and user self diagnose

**Comment by bbookman** [comment]
Bad title. Can't edit on mobile. Remove word "We're"

**Comment by josancamon19** [comment]
You can send a screenshot, and that will report to instabug

**Comment by bbookman** [comment]
1. Instabug is not always functional
2.  The user wishes to have more information - at least a dev user may.  
3. Instabug is not traceable by the user.  If users can report the issue because they can see the error message and report it via GitHub issues, then they can track it.  Not being able to track things feels like throwing information into a void

**Comment by bbookman** [comment]
Please consider reopening this. The bug reporting mechanism with a screenshot seems inadequate at best.
