### ISSUE TITLE
[P4] Optional ability to chat with discards

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#300]
Allow user to optionally chat with discard. I assume the current chat implementation does not. 

Example use case: I want to have chat count the number of times in a day I say "good morning "

**Comment by josancamon19** [comment]
Right now we cannot do inference on all your memories, it's more of QA RAG system, fyi.

This sounds great, low priority, happy to receive PR's.

**Comment by bbookman** [comment]
P3, not MVP
