### ISSUE TITLE
[P3] English icon shows Brit flag. Should it?

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#301]
Is the app really requesting STT with British English?  If not, change the icon. If yes, immediately add US English as option

**Comment by josancamon19** [comment]
No difference

**Comment by bbookman** [comment]
1. The UI is confusing in this regard
2. US English speakers might think there is, in fact, a difference
3. If you mean that the back end does not differentiate between US English and British English, then perhaps NO FLAG is a better solution
4. What happens if you implement Indian English.  I know with Google STT, there is a very marked difference between processing audio against a corpus of British English and US English.  So at least for that API, they are different.

As it stands, the UI is confusing.  I disagree with closing this issue
