### ISSUE TITLE
1.0.6 iOS: No plug in working

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#302]
No plug ins are functioning for me on 1.0.6 iOS

**Comment by josancamon19** [comment]
in progress

**Comment by josancamon19** [comment]
done, but, not released yet

**Comment by bbookman** [comment]
Please do not close without having someone verify that it works.  I posted a recommendation that no issue should be closed without at least minimal verification.   Having at least bare minimum QA would help the community a lot

**Comment by bbookman** [comment]
Confirmed fixed. Although there's a new bug off file in a minute.
