### ISSUE TITLE
Multi-Language Support

### ISSUE THREAD

**Issue by ArchishmanSengupta** [BasedHardware/Friend#308]
The product currently supports voice input processing exclusively in English. To enhance its usability and value, especially for users in non-English speaking countries, i propose the addition of multi-language support.

Languages to Consider:
Mandarin
Hindi
Spanish
French

This help in user accessibility, market expansion and overall user experience

**Comment by josancamon19** [comment]
You can already do that for each language you mentioned, please check in settings.

Maybe is not clear in the app?
