### ISSUE TITLE
App shows -1% when not connected

### ISSUE THREAD

**Issue by ArchishmanSengupta** [BasedHardware/Friend#313]
### The app shows `-1%` when not connected to the device.

The % should only show when the device is connected, and minimum % value should be 0%

<img src="https://github.com/BasedHardware/Friend/assets/71402528/1c21d1e1-0cc2-46f5-ba1b-367869b416e7" alt="IMG_1588" width="400" height="500">

**Comment by ArchishmanSengupta** [comment]
@josancamon19 can you assign me this? can take up.

**Comment by josancamon19** [comment]
Wondering how this is going @ArchishmanSengupta it'd be great if you could create a Draft PR

**Comment by ArchishmanSengupta** [comment]
hi, @josancamon19 due to some unforeseeable reason I am off for a few days, kindly assign this to someone else.

**Comment by raymanyyy** [comment]
Ready for review https://github.com/BasedHardware/Friend/pull/338
The bar is now completely hidden when a Friend is disconnected

**Comment by bbookman** [comment]
IMO P4, not MVP and does not prevent user from full functionality.  It's cosmetic

**Comment by josancamon19** [comment]
Thanks @raymanyyy
