### ISSUE TITLE
When app get's killed, like dismissed it should throw a notification asking to reopen like tesla app does ($100)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Friend#318]
**Is your feature request related to a problem? Please describe.**
The app has to be opened all the time in order for the device to work, could be in the background but not killed.

**Describe the solution you'd like**
When this happens there should be an event that detects this and throws a notification, asking to reopen.
There should be an explanation about it during the onboarding.

**Comment by josancamon19** [comment]
> This should work for android and iOS

**Comment by Becca-Saka** [comment]
I want to pick this up, can you assign me to this?

**Comment by josancamon19** [comment]
Assigned to @Becca-Saka for the next 2 days, please create a draft PR right from the beginning, so we can see your advances on this

**Comment by Becca-Saka** [comment]
@josancamon19

I am done with the first part.

About showing this on the onboarding could you share more insight?

> There should be an explanation about it during the onboarding.

**Comment by josancamon19** [comment]
Hey @Becca-Saka feel free to just do the lint fix I mentioned on the PR, I will test this after, but overall lgtm, and if you could test it on android too, that'd be amazing

**Comment by Becca-Saka** [comment]
> if you could test it on android too, that'd be amazing

updated the android screen record, the link was broken

**Comment by josancamon19** [comment]
Also @Becca-Saka please send me your details for the transfer, thanks!
