### ISSUE TITLE
createNotification util should have an option to navigate the user to certain place of the app when the notification is clicked ($100)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Friend#319]
**Is your feature request related to a problem? Please describe.**
There are some notifications that should redirect to memory detail, or chat page, so to have this util function more useful, this logic should be handled.

**Describe the solution you'd like**
we can call createNotification util with a path that when the notification is triggered and clicked, opens that page is requested.

**Comment by mshahjahan-mufin** [comment]
to @josancamon19 Can you assign this to me?

**Comment by jasonofua** [comment]
hello @josancamon19 can you assign this to me , i can get it done

**Comment by josancamon19** [comment]
Assigned to @mshahjahan-mufin for the next 2 days

**Comment by mshahjahan-mufin** [comment]
to @josancamon19 Thanks for assigning. Can you please change the assignee to this: https://github.com/SHAH-JI ?
Actually, I commented with the wrong Github account

**Comment by SHAH-JI** [comment]
to @josancamon19 Can you assign to this ID? Thanks.

**Comment by josancamon19** [comment]
Done
