### ISSUE TITLE
Include raw transcript during memory export on iOS

### ISSUE THREAD

**Issue by oreHGA** [BasedHardware/Friend#320]
**Is your feature request related to a problem? Please describe.**
Sharing a memory currently provides a .txt file which includes:

- title
- summary
- action items

It will be great to include the raw transcript from the conversation by default.

**Describe the solution you'd like**
Include in the .txt file that the generated the raw transcript 

**Next steps**
- Looking for where the export logic is in the codebase
- Finding where raw transcripts are stored
- Append to the file

**Comment by vinayrkumar** [comment]
It would be great to include the Created at , Between and Category as well along with an option for Raw transcript to be exported. 
Plugins dont have the ability to be exported and needs to be manually copy pasted. Suggest we have an option to share along with the memory from any of the selected plugins as well. ( maybe this should be a seperate issue ? )

**Comment by bbookman** [comment]
IMO P1.  It's P1 as long as there are bugs preventing memory creation or retention.  could drop priority if those are addressed IMO

**Comment by oreHGA** [comment]
Took a look through the codebase. Appending `widget.memory.transcript` to the share function on memory detail page should do the trick https://github.com/BasedHardware/Friend/blob/0104081d5e6aefdeda54610f0cc10e314967260e/apps/AppWithWearable/lib/pages/memory_detail/page.dart#L362

Will get the repo setup when I have some time & attempt a PR

**Comment by josancamon19** [comment]
Not sure about this.

You can export as JSON if you are a dev.
You can export `share` a structured format, which is not structured anymore with the transcript.
You can also copy the transcript if you want to share that raw version.

Closing for now.
