### ISSUE TITLE
When trying to connect to another FRIEND necklace, I have to delete my app with all my memories

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#322]
**Describe the bug**
When trying to use another FRIEND necklace, I have to delete my app with all my memories

**To Reproduce**
1. Connect necklace
2. Disconnect it and try to connect another necklace
3. There will be unlimited search.

**Expected behavior**
A new necklace should have no problems to connect to. I should be able to switch between different necklaces 

**Screenshots**

**Comment by bbookman** [comment]
IMO P2, not core MVP feature

**Comment by josancamon19** [comment]
Fixed on latest Testflight version.
