### ISSUE TITLE
[JUST A THOUGHT] Include location as part of memory creation

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Friend#325]
**Is your feature request related to a problem? Please describe.**
Be able to ask chat or search for memories at home, memories at work, memories in the street, memories in another city, and being able to find them, it's something that sounds interesting to me, not sure if it's worth a feature rn, but happy to chat and make it happen if many people wan it.

**Comment by bbookman** [comment]
This feature request was on my radar as well.  fantastic idea.  memories time/date and location!

**Comment by bbookman** [comment]
IMO P3

**Comment by nathansudo** [comment]
Love this idea as well!
