### ISSUE TITLE
Chat doesn't have the context all the time about stuff even if it's in the memories

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#326]
Video says it all

https://github.com/BasedHardware/Friend/assets/43514161/6636cb79-884a-415c-ac03-71a705e4b699

**Comment by bbookman** [comment]
IMO P0, its core MVP functionality

**Comment by josancamon19** [comment]
To check on latest version, with multitopic search based on request, it should be considerably better.

**Comment by josancamon19** [comment]
repeated issue, keeping the last one
