### ISSUE TITLE
Ability to share memory with more details including from the plugins

### ISSUE THREAD

**Issue by vinayrkumar** [BasedHardware/Friend#328]
**Is your feature request related to a problem? Please describe.**
Go to Memories -> Select memory -> Share memory : Shares the headline of the memory, Summary/ Overview and action items only and not other fields or data which are reflected in the memory tab 

**Describe the solution you'd like**
Ability to share along with what we currently have today : 
Share : Created at ; Between & Category details related to that memory being shared. 
If Plugins are enabled and content exists in the memory : 
Allow selecting specific plugin outputs pertaining to that memory to be shared along with the rest of the memory 

There are no other options other than select all , copy and manually paste the details which are currently missing in the Share memory option

**Comment by bbookman** [comment]
Share and export ;)

**Comment by bbookman** [comment]
IMO P2

**Comment by josancamon19** [comment]
https://github.com/BasedHardware/Friend/issues/382 moving this to here
