### ISSUE TITLE
Integrate One Signal ($100)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Friend#331]
**Is your feature request related to a problem? Please describe.**
https://documentation.onesignal.com/docs/flutter-sdk-setup

We should be able to send updates, notifications, or anything through push notifications to user, about important updates, deals, etc.

**Describe the solution you'd like**
Implement OneSignal integration + user identification on main.dart

**Additional context**
I spent a few hours trying to set it up but this issue always came: https://github.com/OneSignal/OneSignal-Flutter-SDK/issues?q=Multiple+commands+produce

**Comment by taaha161** [comment]
Hello, can I be assigned this task?

**Comment by josancamon19** [comment]
Assigning to @taaha161 for the next 2 days, please create a draft PR and keep updating your owkr

**Comment by mdmohsin7** [comment]
Hi @josancamon19 I have integrated One SIgnal and have tested it on Android. It is working as expected. I also have fixed the `multiple commands produce` error. I currently don't have a paid Apple Developer Account so I am unable to build the iOS App locally (signing issues due to push notifications requiring paid account). Should I open a draft PR so that you can test the build out locally?

**Comment by josancamon19** [comment]
The complex part is iOS unfortunately, not android, so if you can't I will deassign the PR, please let me know

**Comment by mdmohsin7** [comment]
> The complex part is iOS unfortunately, not android, so if you can't I will deassign the PR, please let me know

Understood! I wasn't assigned this issue anyway. I just started working on it directly. I have shared the fix for the `multiple commands produce` error  in the comment of the GitHub issue link you've attached. You can follow those steps to fix that issue and complete the integration.
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/551#issuecomment-2184159953

**Comment by josancamon19** [comment]
Thanks @mdmohsin7 , I'll give it a try in a couple hours and will let you know.

**Comment by josancamon19** [comment]
Tried but still no progress, can I assign it to you, please send me an email with your details to joan.santiago.cabezas@gmail.com, I will give you access to our AppStore team.

**Comment by mdmohsin7** [comment]
> Tried but still no progress

Strange! Are you still getting the same `multiple commands produce` error or a new `cyclic dependency` error? If it's the same error, is it for One Signal specific files only?

> can I assign it to you, please send me an email with your details to joan.santiago.cabezas@gmail.com, I will give you access to our AppStore team.

Sure! I can try. What all details do I have to email?

**Comment by josancamon19** [comment]
Just your email @mdmohsin7

**Comment by mdmohsin7** [comment]
> Just your email @mdmohsin7 

Done! I've sent you an email with the subject `One Signal Integration #331`

**Comment by mdmohsin7** [comment]
~~@josancamon19 after a lot of errors and problems, I finally got the app to build alongside the OneSignal integration. Can you please share the app id for iOS from One Signal dashboard which you might have setup already? Or should I set it up on my personal OneSignal account for testing?~~

**Update:** I checked the Apple Developer Console and didn't find any keys, which means OneSignal wasn't setup. So I created a p8 Key and integrated APN in my personal OneSignal Account and tested it.
Attaching screenshot of the test notification I sent as a proof.

![notification](https://github.com/BasedHardware/Friend/assets/59914433/0ca23c56-6d2c-41e3-972d-61f1b6009156)

**Comment by mdmohsin7** [comment]
@josancamon19 what values do we have to use to identify users?
```
var externalId = "123456789" // You will supply the external id to the OneSignal SDK
OneSignal.login(externalId);
```

**Comment by josancamon19** [comment]
Awesome! you can use Sharedprefs.uid, could you please create a PR for this? so we can merge it today? thanks!

**Comment by josancamon19** [comment]
Also, please DM me your details for the transfer, thanks!
