### ISSUE TITLE
Print or mark ON/OFF in Friend switch

### ISSUE THREAD

**Issue by diegoasua** [BasedHardware/Friend#337]
**Is your feature request related to a problem? Please describe.**
My problem is that there is no way to tell which side is ON and which OFF in the device switch.

**Describe the solution you'd like**
Two options:
- Add some contour to each side of the switch in the STL files marking ON/OFF or some symbols that unmistakably guide the user.
- Post-printing, add marks or stickers.

**Comment by bbookman** [comment]
IMO P2
