### ISSUE TITLE
[P0] Error creating memory

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#339]
I also reported this via the in app screenshot bug reporting tool. So I'm not sure where those go.

My friend captured a gigantic amount of speech to text today and throughout the day got the error about creating a memory. 

And one release I lost all memories

And here I'm also losing memories

I am an unhappy user

**Comment by bbookman** [comment]
the huge amount of text not even discarded it just disappears.

**Comment by bbookman** [comment]
I'm fairly certain the issue has something to do with connectivity.  i have some evidence that when at home with a solid wi-fi / cell connection I do not see this problem.  however when at work with a very poor wifi or cell connection I see these errors.

**Comment by bbookman** [comment]
I propose that a loss of all memories is a P0

**Comment by bbookman** [comment]
Report on discord tampino_the_incredible

Yeah... It's capturing nothing, even when I talk directly into it... So definitely not recording memories. It was working okay in the house yesterday... But not today when I'm out and about

Might be a coincidence, but I have seen a correlation between "listening / memories" capture not working , and my phone switching between wifi / 4g / 5g.

**Comment by bbookman** [comment]
Not sure if this helps diagnose, but I'm getting no audio in my GCP bucket.  This was working as of June 17.

**Comment by bbookman** [comment]
This is environmental @josancamon19 .  When i use friend with good wifi, I do not see this.

**Comment by bbookman** [comment]
I guess my reception is better at work because I am in fact getting memories today

**Comment by josancamon19** [comment]
Thank you @bbookman for the feedback. I've implemented a few layers of handling exceptions, edge cases, so this doesn't happen anymore, still there's room for improvement, will release this version soon.
