### ISSUE TITLE
[P3] No daily summary

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#342]
Got an in app notification that I had a daily summary. None is available

**Comment by josancamon19** [comment]
Can you check /chat page? @bbookman

**Comment by bbookman** [comment]
Sorry this can be closed. I didn't realize it was gonna be in the chat.  My enhancement request would simply be that this could be a separate thing where I see just summaries. A summary page.  

Another possibility would be in the memories page because each memory has a date and time, and then at the end of that day would be a summary on the memories page
