### ISSUE TITLE
Disconnect notifications

### ISSUE THREAD

**Issue by bbookman** [BasedHardware/Friend#346]
tampink_the_incredible:

I understood when buying from  KS that this was mostly developer... I thought I could potentially contribute by adding comments and thoughts from real life usage that may help the developer community. 
Today I noticed that I'm getting memories much more frequently than I did yesterday, when pretty much everything was discarded. At 10:48 a memory was created... Since then until now, nothing, so I assume it disconnected... Granted it's unlikely that I'd notice the lights changing colour on the device, but is this an option when it disconnects... Or a notification to my android smart watch? Needing to check the connection status on a regular basis would be annoying!

**Comment by josancamon19** [comment]
Notifications on disconnection are enabled, I asked on discord more details but user didn't respond.

I will close it for now, but let's reopen if this happens again.
