### ISSUE TITLE
App does not receive audio with New Device Firmware 

### ISSUE THREAD

**Issue by akshaynarisetti** [BasedHardware/Friend#35]
The latest App works with old firmware, but with the new firmware no audio is received

<img src="https://github.com/BasedHardware/Friend/assets/58532023/2579fa8e-6569-429f-8c66-2194db2105cf" alt="issue" width="200" height="500">

**Comment by DamienDeepgram** [comment]
+1 on having this issue with the latest code I tried.

I loaded the firmware yesterday too
