### ISSUE TITLE
LateInitializationError for ENV Instance

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/Friend#354]
**Describe the bug**
Launching the app in debug mode throws the following error
```
 E/flutter ( 6441): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field
'_instance@1152182862' has not been initialized.
[        ] E/flutter ( 6441): #0      Env._instance (package:friend_private/env/env.dart)
[        ] E/flutter ( 6441): #1      Env.mixpanelProjectToken (package:friend_private/env/env.dart:26:46)
[        ] E/flutter ( 6441): #2      MixpanelManager.init (package:friend_private/backend/mixpanel.dart:12:13)
[        ] E/flutter ( 6441): #3      main (package:friend_private/main.dart:23:25)
[   +2 ms] E/flutter ( 6441): <asynchronous suspension>
```

**To Reproduce**
1. Pull the latest changes
2. Setup the code locally
3. Run either the dev or prod flavor

**Expected behavior**
The app was expected to run without any issues

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 12

**Additional context**

**Comment by francip** [comment]
Not sure how this is completed, given that the main branch still has the issue.

Here's a PR - https://github.com/BasedHardware/Friend/pull/358, with a fix, let me know if another fix has been already merged in a different branch.

**Comment by mdmohsin7** [comment]
> Not sure how this is completed, given that the main branch still has the issue.
> 
> Here's a PR - #358, with a fix, let me know if another fix has been already merged in a different branch.

I had this issue occur to me because I was using `lib/main.dart` file as the entrypoint, when it should have been `lib/main_prod.dart` or `lib/main_dev.dart`.

Didn't get the same issue again after changing the entrypoint, hence I closed it.

**Comment by francip** [comment]
It reproes for me with both _prod and _dev entry points.
