### ISSUE TITLE
The Chinese text in the 'Memories' interface of the Android app turns into garbled characters

### ISSUE THREAD

**Issue by dangehub** [BasedHardware/Friend#367]
**Describe the bug**

Despite having selected Chinese in the language settings.
![3db85c3c30ee49147f542e0b5eb9ee70](https://github.com/BasedHardware/Friend/assets/61233621/d3e6d05a-5492-4dff-85d4-be0cc910960f)

The Chinese text in the 'Memories' interface of the Android app turns into garbled characters
![image](https://github.com/BasedHardware/Friend/assets/61233621/ec5f0cfc-a9bc-4e41-bcec-98d97a817519)

But when I click on a specific memory, Chinese characters are displayed correctly.
![image](https://github.com/BasedHardware/Friend/assets/61233621/9ff97f82-c984-4ed0-894f-4d46c1cc5703)

**To Reproduce**
1. Set language to Chinese and try to transcribe
2. Go to 'Memories'
3. See error

**Screenshots**
Attached above.

**Desktop (please complete the following information):**
 - OS: android
 - Version 1.0.10+28

**Smartphone (please complete the following information):**
 - Device:sumsang s23ultra
 - OS: one ui 6.1

**Comment by josancamon19** [comment]
Fixed on latest appstore release!

**Comment by superacac** [comment]
The latest version still has this issue.
