### ISSUE TITLE
On fresh install I am unable to build the project. It fails at "Framework 'opus' not found"

### ISSUE THREAD

**Issue by njerschow** [BasedHardware/Friend#380]
**Describe the bug**
Building in Xcode to run in simulator does not work. The error is Framework 'opus' not found

**To Reproduce**
1. Install flutter, cocoapods, etc
2. run flutter clean, flutter pub get
3. pod install
4. flutter run for iOS simulator
5. See error 

**Expected behavior**
I would expect that running in simulator works without issues?

**Screenshots**

**Desktop (please complete the following information):**
info given in additional context below

**Smartphone (please complete the following information):**
Info given in additonal context below

**Additional context**
Changing current working directory to: /Users/n/Documents/PassiveIncome/AIWearables/friend/apps/AppWithWearable
Connected devices:
Nikita’s iPhone (mobile)        • 00008130-           • ios            • iOS 18.0 22A5282m
iPhone 15 Plus (mobile)         • FA90C1E5-F461-497E-A9D7-• ios            •
com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.1 23B74 darwin-arm64
Chrome (web)                    • chrome                               • web-javascript • Google Chrome 126.0.6478.127

Checking for wireless devices...

[1]: Nikita’s iPhone (00008130-)
[2]: iPhone 15 Plus (FA90C1E5-F461-497E-A9D7-)
[3]: macOS (macos)
[4]: Mac Designed for iPad (mac-designed-for-ipad)
[5]: Chrome (chrome)
Please choose one (or "q" to quit): 2
Launching lib/main.dart on iPhone 15 Plus in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      1,060ms
Xcode build done.                                           37.5s
Failed to build iOS app
Error (Xcode): Framework 'opus' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 15 Plus.

**Comment by josancamon19** [comment]
`dart run build_runner build`

**Comment by njerschow** [comment]
Hey @josancamon19 

I am still getting an issue, even after running this. Here is the output:

```
n AppWithWearable [main]% dart run build_runner build
[INFO] Generating build script completed, took 222ms
[INFO] Reading cached asset graph completed, took 93ms
[INFO] Checking for updates since last build completed, took 1.0s
[INFO] Running build completed, took 15ms
[INFO] Caching finalized dependency graph completed, took 81ms
[INFO] Succeeded after 101ms with 0 outputs (0 actions)
n AppWithWearable [main]% flutter run --flavor prod  
Launching lib/main.dart on iPhone 15 Plus in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        747ms
Xcode build done.                                           20.1s
Failed to build iOS app
Error (Xcode): Framework 'opus' not found


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Could not build the application for the simulator.
Error launching application on iPhone 15 Plus.
```

**Comment by njerschow** [comment]
@josancamon19 - I was able to build and run on my device, but I was not able to get things going on the simulator due to the Opus issue.

For my purposes I am ok with just using my device for dev, but I will leave this comment here for others in case they run into the same issue.

**Comment by cyqiii** [comment]
I run into the same problem :(

@njerschow  Any luck now?

**Comment by likw99** [comment]
Same issue, any update? Thanks.
