### ISSUE TITLE
Memories Include location of the memory ($100)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Friend#384]
**Is your feature request related to a problem? Please describe.**
Location, should simply store Lat Lng of where the memory was created.

And should be displayed beautifully on the memory detail page, with a onClick to maps.

Sort of.
![IMG_0001](https://github.com/BasedHardware/Friend/assets/18078879/a263410f-c63b-4069-bdc2-4cf655c5b4f6)

- Update memory database object.
- Make this coordinates array, optional.
- If available display them on memory detail page.

**Comment by josancamon19** [comment]
Location permissions should be asked seamlessly.

**Comment by mdmohsin7** [comment]
We have to fetch the user's location only once? Or keep fetching it every few mins or something like that?

**Comment by josancamon19** [comment]
Only once, lgtm, where the memory starts probably @mdmohsin7

**Comment by mdmohsin7** [comment]
> Only once, lgtm, where the memory starts probably @mdmohsin7

Wouldn't it make more sense to ask for location (only once) when the user starts recording? As the user will have to interact with the App (especially on iOS) for location (if they only allow one time access). We will have to wait until the user interacts with the location popup before we can start creating a memory.

Also @josancamon19 would like to take this up. I've started working on it.

**Comment by josancamon19** [comment]
Yeah, let's ask only once, what I mean is let's try obtaining the location only where the memory starts.
