### ISSUE TITLE
About Firebase

### ISSUE THREAD

**Issue by ZeusFunk** [BasedHardware/Friend#4]
I've noticed that there are Firebase related configurations in FlutterFlow. Are there any tutorials on how to configure it? Or can I just create a Firebase project with the default settings? Additionally, I hope it can support Supabase because it allows for self-hosting. Thanks. :)

**Comment by akshaynarisetti** [comment]
Hi, the App with Wearable no longer has Firebase Integration for simplicity

**Comment by kodjima33** [comment]
Hey @ZeusFunk - removed it for simplicity
