### ISSUE TITLE
Add Developer Parameter for Custom Transcript Server

### ISSUE THREAD

**Issue by lightningRalf** [BasedHardware/Friend#404]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't use my preferred transcript server. The current setup limits flexibility, making it hard to integrate the app with specialized or self-hosted solutions.

**Describe the solution you'd like**
I'd like a developer parameter in the app to configure:
1. A user-defined transcript server URL.
2. An option to use Deepgram via an API key.
3. The default server provided by basedHardware.

**Describe alternatives you've considered**
Alternatives include creating a fork of the repository to hardcode a custom server, but this adds maintenance overhead and complexity.

**Additional context**
This feature will enhance the app's adaptability, providing users with more control over their transcription needs. It will cater to various requirements for transcription accuracy, speed, and cost.

**Comment by josancamon19** [comment]
1. If you are techie enough to build your own transcript server, you can compile the app and run it yourself
2. You can do that, enable developer mode
3. Will happen, wip
