### ISSUE TITLE
Add Facts page ($2,000)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#410]
**Problem:** Users want to be able to remember interesting things and we need to pass better context to the AI chat about the user

So We need to add a new page called "Facts"

This page should do 2 things: 
- show to users interesting facts they should remember
- let them review facts (separate interesting from not interesting facts) 

Facts should also be used as a context for the AI chat. they should be vectorized and passed as embeddings during the chat conversation on the chat page. 

Here what's needed to be done:

https://excalidraw.com/#json=o5VKPgMUs-KFt3ZOM4Egp,fYMLB6oK7c8kIipnvzx91w

![Image](https://github.com/BasedHardware/Friend/assets/43514161/3719d682-c7d2-4ad4-905f-0821c1a6ec06)

[Here is How other apps do it](https://apps.apple.com/us/app/bee-your-personal-ai/id6480349491)

**More context:**
This data should be stored in the the backend as a separate entity. 

This is a paid task. Reward is $2000 in cash. Simply link your PR with this task and we will check it asap. Check how Contributions and bounties work [here](https://basedhardware.com/contribute)
If no one is assigned to this task, then no one is working on it. We don't lock bounty tasks unless you've created PRs before.

**Comment by SimonBaars** [comment]
Do you imagine there will be four options in the bottom menu? Or will there be an option "conversations" under "memories"?

**Comment by SimonBaars** [comment]
So is this basically just "starring" memories and then having an overview of "starred" memories?

**Comment by Wolfof420Street** [comment]
can I get this assigned to me please?

**Comment by kodjima33** [comment]
> Do you imagine there will be four options in the bottom menu? Or will there be an option "conversations" under "memories"?


4 options

**Comment by kodjima33** [comment]
> So is this basically just "starring" memories and then having an overview of "starred" memories?

yes

**Comment by kodjima33** [comment]
> can I get this assigned to me please?

@Wolfof420Street you can just start working on this, no one is working on it

**Comment by mdmohsin7** [comment]
> 
> 
> > Do you imagine there will be four options in the bottom menu? Or will there be an option "conversations" under "memories"?
> 
> 
> 4 options
> 

So the current `memories` will be renamed to `conversations` and a new tab will be added with the name `memories`. Under the new `memories` tab, the user will be able to see their starred conversations. Am I right?

Wouldn't it create confusion as to what exactly is a memory and a conversation? If memories are just important conversations, then maybe we can have an option under conversations to view only starred conversations?

**Comment by Wolfof420Street** [comment]
> > can I get this assigned to me please?
> 
> @Wolfof420Street you can just start working on this, no one is working on it

already working on this.

**Comment by SimonBaars** [comment]
Let me know if @Wolfof420Street doesn't succeed, I'd be happy to pick it up.

**Comment by josancamon19** [comment]
Will add more details to this task later, for now, I'm sure you've not understood the task completely, and why is it needed. For now, not assigning.

**Comment by kodjima33** [comment]
Task restarted and ready to be taken

**Comment by princezuda** [comment]
I need a little bit of additional context. You want the device to take what users say and for it to use semantic analysis to decide what they said or heard that should be saved to the facts page? Want to clarify before potentially going further.

**Comment by Wolfof420Street** [comment]
can I lock this down now? @josancamon19 @kodjima33 ?

**Comment by Androidsignal** [comment]
@kodjima33 can you assign me?

**Comment by josancamon19** [comment]
Closing this for now, this is a more complex feature, so we will either handle it internally, or add much more context later.

Will reopen later if needed.
