### ISSUE TITLE
Multiple languages diarization fix

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#425]

**Comment by josancamon19** [comment]
This also includes, display language limitations in app.
Allow users to use other languages besides the 8 available right now, but explain that it doesn't have speaker profiles.

Server api only supports english for speaker profiles, needs to be at list in top 5 most used languages.

**Comment by josancamon19** [comment]
Backend diarization fix for languages other than english.
Unfortunately no solution for speech profiles if lang != english.
