### ISSUE TITLE
OpenGlass support - photo control and memory

### ISSUE THREAD

**Issue by francip** [BasedHardware/Friend#432]
https://github.com/BasedHardware/OpenGlass/pull/44 implements the ability to control taking a photo with OpenGlass. It would be nice, if the Friend app would add a feature for those that are using OpenGlass device to take a photo and add it as a memory.

The photo control characteristic is a write-only and supports the following values:
-1 - take a single phot
0 - stop taking photos
5-300 - take a photo every x seconds (round up to the nearest multiple of 5)

The photo is streamed as updates over the photo data read/notify characteristic, as a JPEG, with a terminating packet containing 0xFF 0xFF

**Comment by nathansudo** [comment]
@francip  Would love to see this option for the phone as well!  To take a photo from the phone and add it to the memory as well.   Love the idea of incorporating Openglass into this, ideally you could turn on or off that function easily as you may not want this all the time but in specific cases where you could trigger via voice prompt or the mobile app, but maybe Friend 2 needs a multifunction button as well to initiate some actions.

**Comment by francip** [comment]
Taking a photo memory from the phone should be pretty easy - just add a camera button on the memory tab. But yes, definitely would be useful.
