### ISSUE TITLE
When the client's webhook involves non-English content, UTF-8 encoding issues arise. 

### ISSUE THREAD

**Issue by Beelkic** [BasedHardware/Friend#434]
**Describe the bug**
Through testing, I discovered that when sending requests to the server, the non-English parts appear garbled, while the English content remains unaffected.

**To Reproduce**
1. Open the settings button
2. Enable developer mode
3. Enter the custom webhook URL in advanced mode
4. Notice the returned garbled text on the webhook server
![微信截图_20240713004446](https://github.com/user-attachments/assets/ae7084fb-72b7-4b61-9952-f97bb48f8751)

**Smartphone :**
 - Device: Xiaomi 13 Pro
 - OS: Hyper OS 1.0.24.6.10.DEV

**Comment by nathansudo** [comment]
@mdmohsin7  seems to be working on something that may resolve this issue.

Reference in the Discord

https://discord.com/channels/1192313062041067520/1231903583717425153/1261760653371117658

**Comment by josancamon19** [comment]
Commenting for now, as will be fixed in another issue

**Comment by josancamon19** [comment]
Fixed
