### ISSUE TITLE
UTF-8 Issue in Self-Built Android Client Memories: FormatException: Invalid UTF-8

### ISSUE THREAD

**Issue by Beelkic** [BasedHardware/Friend#435]
**Describe the bug**
When I entered a non-English string, Memories encountered an error.
Branch used: main

**Screenshot**
![微信图片_20240712131737](https://github.com/user-attachments/assets/748a24b5-8693-4ff0-80ff-4978aa459496)
![微信图片_20240712131818](https://github.com/user-attachments/assets/7092d27b-55d5-4cb9-b24e-dbeb6d39603c)

**Smartphone:**
 - Device: Xiaomi 13 Pro
 - OS: Xiaomi Hyper OS 1.0.24.6.10.DEV

**Comment by nathansudo** [comment]
@mdmohsin7 seems to be working on something that may resolve this issue. 

Reference in the Discord

https://discord.com/channels/1192313062041067520/1231903583717425153/1261760653371117658

Thanks @mdmohsin7 !

**Comment by josancamon19** [comment]
Fixed

**Comment by Beelkic** [comment]
> Fixed

Thanks~!
