### ISSUE TITLE
Add Trigger Phrase for turning on and off Friend

### ISSUE THREAD

**Issue by rmeyer137** [BasedHardware/Friend#437]
**The Issue**
This is important for two reasons: 

1. I need to do that all the time cos of company confidential conversations.
2. When the Friend is under a shirt it can look odd for someone reaching under and turning it off with the hardware switch - especially if they are female.

**Possible solution**
It would be great if you could set your own phrases for turn it on and off.  The device should come with some default phrases like "Zip It" to turn it off and perhaps "Let's get started." or "Let's chat" or "Okay, I'm ready" to turn it on.  

It is important to also keep the existing hardware switch intact as this is used by others to ensure the unit is completely off.  

**Alternative Solution**
A subtle tap detection like a double tap or a triple tap would could also help solve the issue and could act as trigger to turn off and back on.  However, a feedback mechanism would be needed to inform the user that the device is back on without looking at it.

**Additional context**
When the unit is off, it should go into a sleep mode, turning off any features like Bluetooth to save power consumption whilestill listening for the key phrases or the alternative tap solution.

**Comment by josancamon19** [comment]
Unfortunately not planned in the near roadmap.
