### ISSUE TITLE
Apple sign-In button unresponsive after dismissal

### ISSUE THREAD

**Issue by s12dar** [BasedHardware/Friend#438]
**Issue description**
When I click the "Sign in with Apple" button and dismiss the Apple ID sign-in bottom sheet, the sheet dismisses, but the loading bar continues to load indefinitely, and the "Sign in with Apple" button becomes unresponsive.

**To Reproduce**
1. Open the app.
2. Click on the "Sign in with Apple" button.
3. Dismiss the Apple ID sign-in bottom sheet.
4. Observe the continuous loading bar and the unresponsive "Sign in with Apple" button.

**Expected behavior**
The Apple ID sign-in bottom sheet should dismiss, and the "Sign in with Apple" button should become clickable again without the loading bar continuing indefinitely.

**Smartphone**
- Device: iPhone 13 Pro
- OS: iOS 17.6
- Browser: Not applicable
- Version: App version 1.0.16

**Additional context**
To recover from this issue, quit the app and open it again.

**Comment by josancamon19** [comment]
Please check here https://discord.com/channels/1192313062041067520/1261819368954789888

**Comment by josancamon19** [comment]
Fixed on latest version

**Comment by s12dar** [comment]
Looks like it hasn't been fixed.
