### ISSUE TITLE
Configure App to allow Multiple Firebase Setups per Flavor

### ISSUE THREAD

**Issue by mdmohsin7** [BasedHardware/Friend#441]
**Is your feature request related to a problem? Please describe.**
While setting up Firebase in Flutter, Firebase generates `google-services.json` file which defines the keys. All the keys are restrcited to a single client (which is identified through the app id or bundle id). There are two flavors currently and the user can't have two different Firebase Apps as configuration of one flavor would override the previous `google-service.json` and `firebase_options.dart` files

**Describe the solution you'd like**
Modifying the code in `main.dart` file to allow user to inject a specific version of FirebaseOptions based on the flavor they have selected.

<img width="301" alt="Screenshot 2024-07-14 at 4 09 06 PM" src="https://github.com/user-attachments/assets/af64340a-5445-4894-b2aa-2632d6727909">

```
  if (F.env == Environment.prod) {
    await Firebase.initializeApp(
      options: prod.DefaultFirebaseOptions.currentPlatform,
    );
  } else {
    await Firebase.initializeApp(
      options: dev.DefaultFirebaseOptions.currentPlatform,
    );
  }
 ```

**Comment by josancamon19** [comment]
Fixed by @mdmohsin7
