### ISSUE TITLE
Webhook and Plugins Integrations: Configuration Option to Ignore/include Discarded Memories

### ISSUE THREAD

**Issue by smian1** [BasedHardware/Friend#446]
## Current Behavior
- All memories, including discarded ones, are sent to the configured webhook
- This results in unnecessary data transfer and processing

## Proposed Feature
Implement a configuration toggle in the webhook settings to filter out discarded memories.

## Technical Requirements
1. Add a new boolean field to the webhook configuration schema (e.g., `ignoreDiscardedMemories`)
2. Implement a UI toggle in the webhook settings labeled "Ignore Discarded Entries"
3. Modify the webhook sending logic to check this flag before processing memories

## Expected Behavior
- When the "Ignore Discarded Entries" option is enabled:
  - Only non-discarded memories are sent to the webhook
  - Discarded memories are filtered out before sending
- When the option is disabled:
  - Current behavior is maintained (all memories sent)
  
  ## Benefits
1. Reduces unnecessary data transfer and processing
2. Improves webhook efficiency and relevance
3. Enhances user control over data forwarding

**Comment by josancamon19** [comment]
I think what makes most sense for now, is to not send the discarded ones at all, as those are mostly random noise, that doesn't need to be stored. This is happening already on latest version, so shouldn't be an issue.

**Comment by josancamon19** [comment]
Let me know if this makes sense for now, we will enhance this data forwarding personalization in the future
