### ISSUE TITLE
Red Light Blinking Continuously After Firmware Update v1.0.3

### ISSUE THREAD

**Issue by smian1** [BasedHardware/Friend#460]
## Device Information
- Device: Seeed Studio XIAO nRF52840 Sense
- Firmware Version: v1.0.3
- Bootloader Version: v9.0.0

## Issue Description
After updating to firmware v1.0.3, the device's red light continuously blinks even when connected to a phone. A small green light next to the red light is also constantly on. This behavior persists despite the device appearing to function normally otherwise.

## Steps to Reproduce
1. Connect the device to a Mac computer
2. Upload the new firmware file (`friend-xiao_nrf52840_ble_sense_-1.0.3.uf2`)
3. Allow the device to reset
4. Press the reset button again
5. Upload the new bootloader file (`update-xiao_nrf52840_ble_sense_bootloader-0.9.0_nosd.uf2`)
6. Connect the device to a phone

## Expected Behavior
The device should indicate its connected state correctly through its LED indicators.

## Actual Behavior
- The red light blinks continuously
- A small green light next to the red light is constantly on
- These light behaviors persist even when the device is connected and functioning

## Additional Information
- The device appears to be working correctly in terms of functionality
- Audio quality and transcription accuracy have noticeably improved with this update
- Reverting to the previous firmware resolves the light indicator issue

## Workaround
Uploading the old firmware temporarily resolves the light indicator problem.

## Request
Please investigate this issue and consider pushing an OTA update to fix the light indicator behavior while maintaining the improved audio and transcription quality.

## Positive Notes
- The sound quality improvement is significant and noticeable
- Transcription accuracy has greatly improved
- These enhancements are highly beneficial and should be maintained

**Comment by francip** [comment]
https://github.com/BasedHardware/Friend/pull/464
