### ISSUE TITLE
Better plugin documentation so that even Nik can submit a plugin

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Friend#469]
- [ ] Ability to test both types of plugins without plugins. (Webhooks)
- [ ] Should it be a JSON? maybe a form, and stored in db?
- [ ] On memory created + on transcript received (ideally live streamed, so super fast, on chunk received)
- [ ] Better plugin documentations. Current one is useless, super confusing.
- [ ] Include images/videos on documentation? tutorials?

**Comment by josancamon19** [comment]
Depends a bit on #429 so working on that first

**Comment by nathansudo** [comment]
I love the title of this issue :)

Also would be great to use this form to create your own plugins that aren't public for everyone else if possible.  Maybe stored locally on the phone (and backup) until you choose to submit it to the community.

**Comment by josancamon19** [comment]
Closing, based on latest docs and setup
