### ISSUE TITLE
Deepgram Hackathon Idea

### ISSUE THREAD

**Issue by DamienDeepgram** [BasedHardware/Friend#483]
## Goal

Reduce the amount of audio being transcribed that does not contain speech in the friend apps.

## Approach

Use a Voice Activity Detector (VAD) in the apps to decide what to transcribe.

- [Silero VAD](https://github.com/snakers4/silero-vad)
- [Flutter Version of Silero VAD](https://github.com/char5742/flutter_silero_vad)

## Example

- 20sec of silence followed by 10 seconds of speech

**Today**

- All 30 seconds are transcribed

**With a VAD**

- Only 10 seconds are transcribed

If you apply this logic to 12 hours per day of recording most likely only a small percentage of the day contains speech

## Benefits

- Longer battery life for your phone
- Less silence being transcribed

**Comment by josancamon19** [comment]
To be implemented in the backend

**Comment by DamienDeepgram** [comment]
Backend sounds good will close this one
