### ISSUE TITLE
Whisper Out returns Gibberish 

### ISSUE THREAD

**Issue by akshaynarisetti** [BasedHardware/Friend#49]
At times when voice isn’t recognized properly or language spoken isn’t English, whisper throws gibberish output as transcription. Apply English filter to Whisper output to sanitize such responses.

How to this?
Only permit English letters, numbers etc.. (Regex should do)

**Comment by DamienDeepgram** [comment]
Whisper will also output things like "Thanks for listening" and other weird things during silence

**Comment by ex3ndr** [comment]
This is easily solvable using whisperx

**Comment by akshaynarisetti** [comment]
That works too

**Comment by Wladefant** [comment]
@DamienDeepgram yeah that is a known bug, even the chatgpt app does that. I agree with @ex3ndr whisperx is the way moving forward for a local setup, plus other specialized services like deepgram

**Comment by akshaynarisetti** [comment]
Closing this, we are now using Deepgram.
