### ISSUE TITLE
Mixed languages support: such as, English with Chinese in the same sentence.

### ISSUE THREAD

**Issue by iamsk** [BasedHardware/Friend#498]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I speak Chinese with some English words.
For now, only accept language in recording settings. This may missed some English brand name.

**Describe the solution you'd like**
I wish all the languages recorded.

**Describe alternatives you've considered**
`ASR ` should do mixed languages.

**Additional context**
No, thanks.

**Comment by josancamon19** [comment]
The only solution for now is to change the language on settings.

There's no way to support this, we are waiting for deepgram to support "multi" language options and expand it to other languages.
