### ISSUE TITLE
Integrate Friend App with Meta Rayban ($10,000)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#511]
**Is your feature request related to a problem? Please describe.**
Meta rayban has a useless mobile app. If we integrate Friend app with Meta Rayban, we could help their users to finally get value from AI

**Describe the solution you'd like**
You need to integrate meta rayban's glasses with friend app so that it could stream audio to the app in the same way that Friend necklace does. For pictures, you need to make sure that whenever a picture is taken, it is also sent to Friend app.

**Describe alternatives you've considered**
Meta rayban has a microphone and images but doesn't have SDK out-of the-box. That's what you need to figure out:
- either writing new firmware for meta rayban
- or make Friend app work with Meta raybans by simulating that  it's their native app

**Additional context**
Please don't try to achieve the task by simply creating a streaming via Instagram - it will kill battery very quick. Battery should last for at least few hours. 

This is a paid task. Reward is $10,000 in cash. Simply link your PR with this task and we will check it asap

**Comment by acemtp** [comment]
so... Friend is an "opensource AI wearable necklace" but the biggest bounty is to make a close source product to. work with your the app? I really love your initial idea of Friend but come on, you should first make your AI wearable necklace working correctly with the app before trying to do other things. KISS

**Comment by legut2** [comment]
> so... Friend is an "opensource AI wearable necklace" but the biggest bounty is to make a close source product to. work with your the app? I really love your initial idea of Friend but come on, you should first make your AI wearable necklace working correctly with the app before trying to do other things. KISS

Nothing about this is simple. Seems to be the focus is on friend and less on openglass. Might be simpler to focus on one hardware project rather than two. So in a way, it might be simpler? The focus seems to be less on openglass which in a way could be good, but if being ideologically consistent is important then maybe it makes sense to take this budget and provide it for openglass.

**Comment by acemtp** [comment]
There a millions of things to do with Friend, why splitting the money/time/energy instead of focus on one thing and do it perfectly!

**Comment by josancamon19** [comment]
Will reopen soon.
