### ISSUE TITLE
The current self-built version of the APP seems unable to properly capture and transcribe audio, staying in the listening state continuously.

### ISSUE THREAD

**Issue by Beelkic** [BasedHardware/Friend#520]
**Describe the bug**
Recently, when building the Friend APP, I found that after the build was completed, it kept getting stuck on "Listening" (as shown in the picture below) during use. I'm not sure what went wrong. My backend program is also set up and currently shows no error messages; theoretically, it should be functioning normally. Did I make a mistake somewhere? Looking forward to your response.

![549cd3d8a456d1659175ed733565017](https://github.com/user-attachments/assets/bf8c660a-d4d3-481c-b1b0-23032867e573)

Thank you very much for the excellent work by BasedHardware. Friend has solved many problems in my life (recording, summarizing, intelligent applications). I have also been introducing Friend to my friends, and quite a few of them have built it themselves.

**Comment by josancamon19** [comment]
Hey @Beelkic  can you share a bit more context?
Are you running your own backend?
Which firmware version are you running?
What language?

THanks

**Comment by Beelkic** [comment]
Thank you very much for your response. I apologize for not providing complete information earlier. Here are the detailed details:

Use V1.0.2 Firmware Build

Language: I am currently using English and Chinese for conversations. Friend sometimes recognizes English normally, but for non-English conversations, it always stays in the "listening" state.

Background running: I tried both background running and non-background running, but neither could transcribe.

> Hey @Beelkic  can you share a bit more context?
> Are you running your own backend?
> Which firmware version are you running?
> What language?
> 
> THanks

**Comment by Beelkic** [comment]
Backend: Yes, I am running my own backend, but I haven't seen my self-built friend app interacting with my backend via WS. Then I noticed there is a new version of the Android beta test app on GitHub release. Actually, the latest version of the Android beta test has already solved the issue of being stuck in the listening state that I mentioned.

https://github.com/BasedHardware/Friend/releases/tag/1.0.20-beta-release


> Thank you very much for your response. I apologize for not providing complete information earlier. Here are the detailed details:
> 
> Use V1.0.2 Firmware Build
> 
> Language: I am currently using English and Chinese for conversations. Friend sometimes recognizes English normally, but for non-English conversations, it always stays in the "listening" state.
> 
> Background running: I tried both background running and non-background running, but neither could transcribe.
> 
> > Hey @Beelkic  can you share a bit more context?
> > Are you running your own backend?
> > Which firmware version are you running?
> > What language?
> > 
> > THanks
> 
>

**Comment by josancamon19** [comment]
Awesome!
