### ISSUE TITLE
Summarization

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#55]
We need to add summarization of conversations to an AppWithWearable

The summarization is implemented in AppStandalone => we just need to move it to AppWithWearable

Summarization should be saved by chunks of conversations.

Chunks are cut by a 30-seconds pause

For example, if there is a long conversation of 1h, the summarization chunk will be 1h.

if there is a 30-seconds, it is considered a new conversation. For example
2 people talked for 5 minutes (chunk), then one of them left to a restroom for 2 minutes. After coming back, they continuted to talk again for 10 minutes. Those will be 2 different chunks of 5 and 10 mintes

See good examples how it was done in AppStandalone  
![CleanShot 2024-04-26 at 20 38 07](https://github.com/BasedHardware/Friend/assets/43514161/31ac94a6-318c-4c60-abfc-bb8ee2e88ffd)

**Comment by josancamon19** [comment]
Summarization completed.
