### ISSUE TITLE
Received empty audio data array (V1 Firmware Build)

### ISSUE THREAD

**Issue by felyu** [BasedHardware/Friend#68]
Hello everyone,

I've successfully installed the [V1 Release of the Firmware](https://github.com/BasedHardware/Friend/releases/tag/v1.0.0-firmware) on the chip, and the device is recognized with the LED blinking as expected.

However, upon testing it using either the Python script on my laptop or the [online firmware tester tool (Chrome)](https://basedhardware.github.io/firmware-tester/), I encountered the following errors:

**Python Script Logs:**

```
Recording audio...
Recording stopped
0
Warning: Received empty audio data array.
```

**Online Firmware Tester Tool Logs:**

```
Starting Bluetooth...
Bluetooth started: started
Opening device...
Device opened: Friend (zkSRZ5uwGXfndd3Ka6qSIQ==)
Service: 19b10000-e8f2-537e-4f6c-d104768a1214
- Characteristic: 19b10001-e8f2-537e-4f6c-d104768a1214
  - canRead: true
  - canWrite: false
  - canNotify: true
- Characteristic: 19b10002-e8f2-537e-4f6c-d104768a1214
  - canRead: true
  - canWrite: false
  - canNotify: false
Target protocol found: pcm-8
Waiting for data...
Total received: 0 bytes, speed: 0 bytes/sec, lost: 0 packets or 0 packets
Total frames: 0
Decoding...
Done!
```

Additional Information:
- MacBook Air Early 2015 running Monterey 12.6
- I've attempted to reinstall the software multiple times without success.

I would greatly appreciate any assistance in resolving these issues. Thank you in advance!

**Comment by after-ephemera** [comment]
@felyu can you confirm whether this is still a problem?

**Comment by indelib** [comment]
> @felyu can you confirm whether this is still a problem?

I've bought a the latest Macbook Air M3 and it's now working!!!
