### ISSUE TITLE
Gauge of the wire

### ISSUE THREAD

**Issue by bojrick** [BasedHardware/Friend#78]
I have been trying to use recommended 26mm gauge wire to solder on the seed studio, and having hard time, does anyone suggest better size, that's easy.

What was your experience when you soldered the wires!?

**Comment by eng1n88r** [comment]
I used 22AWG, worked fine for me. It is very tiny contacts on the back of the chip. I usually apply some alloy on the contacts first, and then solder wires.

**Comment by DamienDeepgram** [comment]
FYI https://github.com/BasedHardware/Friend/pull/32

**Comment by bojrick** [comment]
I ended up using 26 gauge recommended wire, I think I mistakenly ordered 18 gauge.
