### ISSUE TITLE
Cloud update for firmware ($500)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#88]
Firmware on Friend's wearable should be able to be updated via cloud

[reference](https://brilliant.xyz/products/monocle)

Ideal scenario: 
All friend's firmware should check our github folder and auto-update once it has internet connection>

"ok" scenario: Friend's firmware should be able to update via the mobile app "appwithwearable"

User-story: As a user, I want to be able to open Friend's app, connect to my wearable, then click "update". It should update the firmware from github

**Comment by akshaynarisetti** [comment]
Resources to help solve the issue: https://github.com/adafruit/Adafruit_nRF52_Bootloader/pull/291


https://enzolombardi.net/adding-ota-firmware-update-support-to-xiao-ble-boards-3db6f034c1fa


https://github.com/0hotpotman0/Adafruit_nRF52_Bootloader

**Comment by after-ephemera** [comment]
So it looks like with the bootloader in place, we should be able to utilize nordic's [swift](https://nordicsemiconductor.github.io/IOS-DFU-Library/documentation/nordicdfu/) and [java](https://github.com/NordicSemiconductor/Android-DFU-Library) libraries to do the updating for us from the app. Adafruit's bluefruit le connect app is an example (see [this dir](https://github.com/adafruit/Bluefruit_LE_Connect_v2/tree/master/Bluefruit/Model/Modules/Dfu)).

**Comment by eng1n88r** [comment]
Did more research on the topic:

- Information on Zephyr DFU [here](https://devzone.nordicsemi.com/f/nordic-q-a/100061/dfu-in-zephyr-nsc-2-3-0) with links to [FOTA](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/device_guides/working_with_nrf/nrf52/developing.html#fota-updates) and the [guide](https://devzone.nordicsemi.com/guides/nrf-connect-sdk-guides/b/software/posts/ncs-dfu)

**Comment by francip** [comment]
Initial implementation of firmware changes to support the OTA DFU, and a rudimentary button to trigger update from app asset currently in https://github.com/francip/Friend/tree/francip-ota-update-client

Known issues:
- need to instruct current users to update the bootloader to min v0.8.0, preferably to v0.9.0 using uf2 file (instructions in firmware/readme.md)
- need to produce new firmware v1.0.3 uf2 file
- going forward need to produce both uf2 file and a zip file for future firmware versions. UF2 will be used for manual update for advanced users, zip will be used by the app for OTA DFU
- need to add app changes to properly deal with OTA state and progress tracking

**Comment by francip** [comment]
https://github.com/BasedHardware/Friend/pull/207

**Comment by francip** [comment]
The firmware changes have landed.
