### ISSUE TITLE
Unable to find Friend device from AppWithWearable on Android w/o manually granting location permision

### ISSUE THREAD

**Issue by jhsu** [BasedHardware/Friend#92]
The app can't find the Friend device unless going into App Permissions and manually granting location permissions.

Device: Pixel 8 Pro
OS: Android 14

The user should be prompted when launching the app for all necessary permissions.

Note: It did prompt me for nearby devices and notifications

**Comment by akshaynarisetti** [comment]
Related to https://github.com/pauldemarco/flutter_blue/issues/336

**Comment by akshaynarisetti** [comment]
Solution: If platform is Android ask for extra GPS permission for Bluetooth to work

**Comment by AshishSardana** [comment]
Is it possible for Android users to share the app (.apk or something else)?
iOS app can be directly downloaded by anyone but Android users require to build it from scratch.

**Comment by Bentlybro** [comment]
@AshishSardana yeah we are working on releasing a apk, will be done soon 🙏 
+ we are working on releasing the app to google play store, this is a work in progress

**Comment by AshishSardana** [comment]
Thanks @Bentlybro! I'll be the first one to try and report/fix any issues in it.

**Comment by AshishSardana** [comment]
Team, if there's an early version of Android apk that can be tested, I'm all in.
